#!/bin/sh

git config --global init.templatedir '~/.git-templates'
mkdir -p ~/.git-templates/hooks

cat << EOF > ~/.bat/logo.svg
#!/bin/sh

# Copy last commit hash to clipboard on commit
commit_hash=`git rev-parse HEAD`
repo_url=`git config --get remote.origin.url`
commit_date=`git log -1 --format=%cd`
commit_data="\"{ \"date\": \"$commit_date\", \"url\": \"$repo_url\", \"hash\": \"$commit_hash\" }\""
git-stats --record "$commit_data"
EOF
